version: '3'

services:

  namenode:
    image: fapereira1/hadoop-namenode:1.0.0
    container_name: namenode
    volumes:
      - /tmp/hdfs/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "9870:9870"
    networks:
      hadoopnet:
        ipv4_address: 172.27.1.5

  datanode:
    image: fapereira1/hadoop-datanode:1.0.0
    container_name: datanode
    volumes:
      - /tmp/hdfs/datanode:/hadoop/dfs/data
      - ./bank:/bank
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    depends_on:
      - namenode
    ports:
      - "9864:9864"
    networks:
      hadoopnet:
        ipv4_address: 172.27.1.6

  hive-server:
    image: fapereira1/hive:1.0.0
    container_name: hive-server
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    depends_on:
      - hive-metastore
    networks:
      hadoopnet:
        ipv4_address: 172.27.1.7
        
  hive-metastore:
    image: fapereira1/hive:1.0.0
    container_name: hive-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    depends_on:
      - hive-metastore-postgresql
    networks:
      hadoopnet:
        ipv4_address: 172.27.1.8

  hive-metastore-postgresql:
    image: fapereira1/hive-metastore-postgresql:1.0.0
    container_name: hive-metastore-postgresql
    depends_on:
      - datanode
    networks:
      hadoopnet:
        ipv4_address: 172.27.1.9
    
  spark-master:
    image: fapereira1/spark-master:1.0.0
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    env_file:
      - ./hadoop-hive.env
    networks:
      hadoopnet:
        ipv4_address: 172.27.1.10

  spark-worker:
    image: fapereira1/spark-worker:1.0.0
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    env_file:
      - ./hadoop-hive.env
    networks:
      hadoopnet:
        ipv4_address: 172.27.1.11

networks:
  hadoopnet:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16