version: '3.4'

services:
  postgres:
    image: fapereira1/hive-postgres:0.0.1
    container_name: postgres
    hostname: postgres.bigdatacluster
    volumes:
      - postgres_pgdata:/var/lib/postgresql/data/pgdata
    networks:
      bigdatacluster:
        aliases:
           - postgres.bigdatacluster.com
    ports:
      - 5432:5432

  hadoop-namenode:
    image: fapereira1/hadoop-namenode:0.0.1
    container_name: hadoop-namenode
    hostname: hadoop-namenode.bigdatacluster
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      bigdatacluster:
        aliases:
          - namenode.bigdatacluster.com
    environment:
      - CLUSTER_NAME=bigdatacluster
    env_file:
      - ./bigdata-cluster.env
    ports:
      - 50070:50070
      - 8020:8020

  hadoop-datanode1:
    image: fapereira1/hadoop-datanode:0.0.1
    container_name: hadoop-datanode1
    hostname: hadoop-datanode1.bigdatacluster
    depends_on:
      - hadoop-namenode
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
      - ./bank:/bank
    networks:
      bigdatacluster:
        aliases:
          - datanode1.bigdatacluster.com
    env_file:
      - ./bigdata-cluster.env

  hadoop-datanode2:
    image: fapereira1/hadoop-datanode:0.0.1
    container_name: hadoop-datanode2
    hostname: hadoop-datanode2.bigdatacluster
    depends_on:
      - hadoop-namenode
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    networks:
      bigdatacluster:
        aliases:
          - datanode2.bigdatacluster.com
    env_file:
      - ./bigdata-cluster.env
  
  yarn-resourcemanager:
    image: fapereira1/hadoop-resourcemanager:0.0.1
    container_name: yarn-resourcemanager
    hostname: yarn-resourcemanager.bigdatacluster
    networks:
      bigdatacluster:
        aliases:
          - resourcemanager.bigdatacluster.com
    depends_on:
      - hadoop-namenode
    env_file:
      - ./bigdata-cluster.env
    ports:
      - 8088:8088

  yarn-historyserver:
    image: fapereira1/hadoop-historyserver:0.0.1
    container_name: yarn-historyserver
    hostname: yarn-historyserver.bigdatacluster
    depends_on:
      - yarn-resourcemanager
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    networks:
      bigdatacluster:
        aliases:
          - historyserver.bigdatacluster.com
    env_file:
      - ./bigdata-cluster.env
    ports:
      - 8188:8188
  
  yarn-nodemanager1:
    image: fapereira1/hadoop-nodemanager:0.0.1
    container_name: yarn-nodemanager1
    hostname: yarn-nodemanager1.bigdatacluster
    networks:
      bigdatacluster:
        aliases:
          - nodemanager1.bigdatacluster.com
    depends_on:
      - yarn-resourcemanager
    env_file:
      - ./bigdata-cluster.env
    ports:
      - 8042:8042

  hive-metastore:
    image: fapereira1/hive-metastore:0.0.1
    container_name: hive-metastore
    hostname: hive-metastore.bigdatacluster
    networks:
      bigdatacluster:
        aliases:
          - hivemetastore.bigdatacluster.com
    depends_on:
      - postgres
    env_file:
      - ./bigdata-cluster.env
    command: /opt/hive/bin/hive --service metastore

  hive-server:
    image: fapereira1/hive-server:0.0.1
    container_name: hive-server
    hostname: hive-server.bigdatacluster 
    networks:
      bigdatacluster:
        aliases:
          - hiveserver.bigdatacluster.com
    depends_on:
     - hive-metastore
    env_file:
      - ./bigdata-cluster.env
    ports:
      - 10002:10002

  spark-master:
    image: fapereira1/spark-master:0.0.1
    container_name: spark-master
    hostname: spark-master.bigdatacluster
    networks:
      bigdatacluster:
        aliases:
          - sparkmaster.bigdatacluster.com
    volumes:
      - spark_master_logs:/var/log/spark-master   
    depends_on:
      - yarn-resourcemanager
    env_file:
      - ./bigdata-cluster.env
    ports:
      - 8080:8080
  
  spark-worker1:
    image: fapereira1/spark-worker:0.0.1
    container_name: spark-worker1
    hostname: spark-worker1.bigdatacluster
    networks:
      bigdatacluster:
        aliases:
          - sparkworker1.bigdatacluster.com
    volumes:
      - spark_worker1_logs:/var/log/spark-worker   
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=sparkmaster.bigdatacluster.com:7077
    env_file:
      - ./bigdata-cluster.env

  hue:
    image: gethue/hue:20191107-135001
    container_name: hue
    hostname: hue.bigdatacluster
    dns: 8.8.8.8
    ports:
      - "8888:8888"
    volumes:
      - ./hue-overrides.ini:/usr/share/hue/desktop/conf/z-hue.ini
    depends_on:
      - "postgres"
      - "hadoop-namenode"
      - "hadoop-datanode1"
      - "hadoop-datanode2"
      - "yarn-resourcemanager"
      - "yarn-historyserver"
      - "hive-server"
      - "hive-metastore"
      - "spark-master"
      - "spark-worker1"
    networks:
      bigdatacluster:
        aliases:
          - hue.bigdatacluster.com
volumes:
  postgres_pgdata:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_historyserver:
  spark_master_logs:
  spark_worker1_logs:

networks:
  bigdatacluster:
    external: true