CREATE USER hive;
ALTER USER hive WITH PASSWORD 'hive';
ALTER ROLE hive SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;

CREATE DATABASE metastore;
GRANT ALL PRIVILEGES ON DATABASE metastore TO hive;

CREATE USER airflow;
ALTER USER airflow WITH PASSWORD 'airflow';
CREATE DATABASE airflow;
GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;

CREATE DATABASE hue;